
server:
  port: 10000

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
 # routes:
  #  api-a:
   #   path: /api-a/*
    #  serviceId: service-dept-c
   # api-b:
    #  path: /api-b/*
     # serviceId: service-emp-c
  host:
    connection-request-timeout-millis: 60000
    connect-timeout-millis: 60000
    socket-timeout-millis: 40000
ribbon:
  ReadTimeout: 10000
  ConnectionTimeout: 10000